version: '3.8'
services:
  movies:
    image: suryamurali96/dockpromovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: suryamurali96/dockprotrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  recharge:
    image: suryamurali96/dockprorecahrge:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  dth:
    image: suryamurali96/dockprorecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
